config/routes.rb
Rails.application.routes.draw do
  #resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  #Create a websocket connection
  #With websockets we do not need HTTP Methods
  #So we can take out the resource comment
  mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: {draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged
  #Checks that body and title exist in the create command
  validates_presence_of :title, :body

  belongs_to :topic, optional: true

  #Dependent destroy allows us to delete all the blogs of the user
  #If the user deletes his account
  has_many :comments, dependent: :destroy

  def self.special_blogs
    all
  end

  def self.featured_blogs
    limit(2)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  #It will go inside the layout directory and will search for blog
  #The css file of blog must be declared in the assets.rb inside the config folder
  layout "blog"

  #What actions we want everyone can access
  #What can't a regular user do
  #site_admin can do everything
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    #binding.pry
    @blogs = Blog.page(params[:page]).per(5)
    #binding.pry
    #@blogs = Blog.featured_blogs
    #binding.pry

    ##Puts Debugging
    #puts "*" * 500
    #puts @blogs.inspect
    #puts "*" * 500

    #Byebug allows us to have a type of breakpoint to debug
    #byebug
    @page_title = "My Portfolio Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    #Includes allows us to get also the comments of that blog
    @blog = Blog.includes(:comments).friendly.find(params[:id])
    @comment = Comment.new
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    #@blog.published! if @blog.draft? this way was cancelling each other
    #@blog.draft! if @blog.published?

    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: 'Post status has been updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 50
  end
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
  <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>
  <% if logged_in?(:site_admin) %>
    <p class="blog-post-meta">
      <%= link_to blog.status, toggle_status_blog_path(blog) %> / 
      <%= link_to 'Edit', edit_blog_path(blog) %> /
      <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>

  <p><%= blog.body %></p>
</div><!-- /.blog-post -->



<!--<tr>
  <td></td>-->
  <!-- Check the time ago a blog was posted -->
  <!--<td>Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</td>-->
  <!--<td><%= blog.body %></td>-->
  <!--<td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>-->
  <!--<td><%= link_to 'Show', blog %></td>-->
  <!--<td><%= link_to 'Edit', edit_blog_path(blog) if logged_in?(:site_admin) %></td>-->
  <!--<td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %></td>-->
<!--</tr>-->

app/views/blogs/_form.html.erb
<!-- Form tag automatically generates an authenticity token for us -->
<!-- FOR CRUD OPERATIONS, CREATE A FORM_FOR, NOT FORM_TAG!!! -->
<!-- FORM_TAG IS USED FOR SEARCH OPERATIONS ETC. -->

<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <%= blog.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, class: 'form-control', placeholder: "Title", placeholder: "Title" %>
  </div>

  <div class="form-group">
    <%= f.text_area :body, class: 'form-control', rows: 15, placeholder: "Content" %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>











<!--<%= form_tag(blogs_path) do %>
  <div class="form-group">
    <%= label_tag "blog[title]", "Blog Title"%>
    <%= text_field_tag "blog[title]", nil, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag "blog[body]", "Blog Content"%>
    <%= text_field_tag "blog[body]", nil, class:"form-control", rows: 15 %>
  </div>

  <div class="form-group">
    <%= submit_tag "Save", class: "btn btn-primary" %>
  </div>
<% end %>-->

app/views/blogs/edit.html.erb
<div class ="col-sm-8 blog-main">

  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">

  <%= paginate @blogs %>
  
  <%= render @blogs %>

  <%= paginate @blogs %>

</div><!-- /.blog-main -->

app/views/blogs/new.html.erb
<div class ="col-sm-8 blog-main">
  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">
  <h2><%= @blog.title %></h2>
  <%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin) %>
  <p><%= @blog.body %></p>

  <!-- Start of comment form-->
  <%= render "comments/comment_form" %>
  <!-- End of comment form -->

  <!-- Start of comments -->
  <div id="comments" data-blog-id="<%= @blog.id %>">
    <%= render @blog.comments %>
  </div>
  <!-- End of comments -->


</div>

<!--<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin) %> |
<%= link_to 'Back', blogs_path %>-->